name: Kraftwerk
author: Minota
version: 1.0.0
description: Plugin for managing UHCs.
main: pink.mino.kraftwerk.Kraftwerk
commands:
  heal:
    description: Heals you or a given player.
  feed:
    description: Feeds you or a given player.
  clear:
    description: Clears you or a given player's inventory.
    aliases:
      - ci
  cleareffects:
    description: Clears you or a given player's potion effects.
    aliases:
      - ce
  fly:
    description: Toggles you or a given player's flight.
  gm:
    description: Changes you or a provided player's gamemode.
  gamemode:
    description: Changes you or a provided player's gamemode.
  gmsp:
    description: Changes you or a provided player's gamemode to Spectator.
  gmc:
    description: Changes you or a provided player's gamemode to Creative.
  gms:
    description: Changes you or a provided player's gamemode to Survival.
  gma:
    description: Changes you or a provided player's gamemode to Adventure.
  pm:
    description: Sends a message to your team.
  pmc:
    description: Sends your coordinates to your team.
  team:
    description: General team commands.
  health:
    description: Gets the health of a given user.
    aliases:
      - h
  whitelist:
    description: Whitelist settings/config.
    aliases:
      - wl
  pregen:
    description: Creates and pregenerates your world.
    aliases:
      - pregenerate
      - createworld
      - cw
  config:
    description: Opens the configuration for UHC.
    aliases:
      - uhc
  editconfig:
    description: Edits the configuration for UHC.
    aliases:
      - edituhc
  message:
    aliases:
      - msg
      - tell
      - whisper
    description: Privately message a user.
  reply:
    aliases:
      - r
    description: Privately reply to a user.
  split:
    description: Split your enchants.
  world:
    aliases:
      - w
    description: Main command for the world manager.
  scatter:
    aliases:
      - sct
      - sca
      - sctter
      - spread
      - scat
    description: Randomly scatter players across a world.
  clearchat:
    aliases:
      - cc
    description: Clears the chat.
  regenarena:
    description: Regenerates the arena.
  arena:
    aliases:
      - a
    description: Joins the FFA arena.
  spawn:
    aliases:
      - lobby
    description: Joins the spawn.
  start:
    aliases:
      - startuhc
    description: Starts a UHC game.
  end:
    aliases:
      - endgame
      - enduhc
    description: Ends a UHC game.
  pvp:
    description: Enables/disables PvP.
  border:
    aliases:
      - shrink
    description: Sets the border for the current UHC world.
  winner:
    description: Sets the winners for the current UHC game.
  killtop:
    aliases:
      - kt
    description: Gets the current top killers in the current UHC game.
  latescatter:
    aliases:
      - ls
    description: Latescatters the provided player.
  matchpost:
    aliases:
      - mp
    description: Set the hosts.uhc.gg matchpost for your game.
  scenarios:
    aliases: 
      - scen
    description: View all active scenarios.
  scenariomanager:
    aliases:
      - sm
    description: Manage scenarios.
  spectate:
    aliases:
      - spec
    description: Spectate the UHC game.
  specchat:
    aliases:
      - sc
    description: Talk in spectate chat.
  helpop:
    aliases:
      - ho
    description: Ask hosts for help.
  helpopreply:
    aliases:
      - hr
    description: Reply to helpop requests.
  tp:
    aliases:
      - teleport
    description: Teleport command.
  tppos:
    aliases:
      - teleportpos
    description: Teleport to position command.
  statistics:
    aliases:
      - stats
    description: View the stats of a player.
depend:
  - ProtocolLib
  - JDA
  - Vault
  - Citizens
  - LiteBans