name: Kraftwerk
author: Minota
version: 1.2.0
description: Plugin for managing UHCs.
main: pink.mino.kraftwerk.Kraftwerk
commands:
  heal:
    description: Heals you or a given player.
  feed:
    description: Feeds you or a given player.
  clear:
    description: Clears you or a given player's inventory.
    aliases:
      - ci
  cleareffects:
    description: Clears you or a given player's potion effects.
    aliases:
      - ce
  fly:
    description: Toggles you or a given player's flight.
  gm:
    description: Changes you or a provided player's gamemode.
  gamemode:
    description: Changes you or a provided player's gamemode.
  gmsp:
    description: Changes you or a provided player's gamemode to Spectator.
  gmc:
    description: Changes you or a provided player's gamemode to Creative.
  gms:
    description: Changes you or a provided player's gamemode to Survival.
  gma:
    description: Changes you or a provided player's gamemode to Adventure.
  pm:
    description: Sends a message to your team.
  pmc:
    aliases:
      - sendcoords
      - coords
      - tl
    description: Sends your coordinates to your team.
  team:
    description: General team commands.
  health:
    description: Gets the health of a given user.
    aliases:
      - h
  whitelist:
    description: Whitelist settings/config.
    aliases:
      - wl
  pregen:
    description: Creates and pregenerates your world.
    aliases:
      - pregenerate
      - createworld
      - cw
  config:
    description: Opens the configuration for UHC.
    aliases:
      - uhc
      - conf
  editconfig:
    description: Edits the configuration for UHC.
    aliases:
      - edituhc
  message:
    aliases:
      - msg
      - tell
      - whisper
    description: Privately message a user.
  reply:
    aliases:
      - r
    description: Privately reply to a user.
  split:
    description: Split your enchants.
  world:
    aliases:
      - w
    description: Main command for the world manager.
  clearchat:
    aliases:
      - cc
    description: Clears the chat.
  regenarena:
    description: Regenerates the arena.
  arena:
    aliases:
      - a
      - practice
      - ffaarena
      - prac
    description: Joins the FFA arena.
  spawn:
    aliases:
      - lobby
      - hub
    description: Joins the spawn.
  start:
    aliases:
      - startuhc
    description: Starts a UHC game.
  end:
    aliases:
      - endgame
      - enduhc
    description: Ends a UHC game.
  pvp:
    description: Enables/disables PvP.
  border:
    aliases:
      - shrink
    description: Sets the border for the current UHC world.
  winner:
    description: Sets the winners for the current UHC game.
  killtop:
    aliases:
      - kt
    description: Gets the current top killers in the current UHC game.
  latescatter:
    aliases:
      - ls
      - sct
      - sca
      - sctter
      - spread
      - scat
      - scatter
    description: Latescatters the provided player.
  matchpost:
    aliases:
      - mp
    description: Set the hosts.uhc.gg matchpost for your game.
  scenarios:
    aliases: 
      - scen
    description: View all active scenarios.
  scenariomanager:
    aliases:
      - sm
    description: Manage scenarios.
  spectate:
    aliases:
      - spec
    description: Spectate the UHC game.
  specchat:
    aliases:
      - sc
    description: Talk in spectate chat.
  helpop:
    aliases:
      - ho
    description: Ask hosts for help.
  helpopreply:
    aliases:
      - hr
    description: Reply to helpop requests.
  tp:
    aliases:
      - teleport
    description: Teleport command.
  tppos:
    aliases:
      - teleportpos
    description: Teleport to position command.
  statistics:
    aliases:
      - stats
    description: View the stats of a player.
  discord:
    aliases:
      - disc
    description: Get the invite link for the discord server.
  apply:
    aliases:
      - staffapply
    description: Get the staff application link.
  cancel:
    aliases:
      - cancelmp
    description: Cancels the awaiting game.
  teaminventory:
    aliases:
      - teaminv
      - ti
      - teami
    description: View your team inventory.
  moles:
    aliases:
      - mole
    description: Base command for mole commands.
  molechat:
    aliases:
      - mcc
    description: Communicate with other moles.
  molekit:
    aliases:
      - mk
    description: Receives your mole kit.
  moleloc:
    aliases:
      - mcl
    description: Send your location to other moles.
  molelist:
    aliases:
      - mcp
    description: View the list of other moles.
  rules:
    aliases:
      - rul
    description: View the server rules.
  store:
    aliases:
      - donate
    description: View the server donation store.
  near:
    aliases:
      - nearby
      - nearbyplayers
    description: View nearby players within a 200 player radius.
  voteyes:
    aliases:
      - "yes"
    description: Votes yes to the current poll.
  voteno:
    aliases:
      - "no"
    description: Votes no to the current poll.
  startvote:
    description: Starts a 15 seconds yes/no poll.
  force:
    description: Force events to happen in the UHC game.
  ping:
    aliases:
      - ms
    description: View a player's ping.
  respawn:
    aliases:
      - revive
      - res
    description: Respawns a player.
  editpregen:
    aliases:
      - ep
    description: Edits the pregeneration configuration.
depend:
  - ProtocolLib
  - JDA
  - Vault
  - Citizens
  - LiteBans
  - HolographicDisplays